version: '3.8'
services:
  auth-service:
    build: .
    ports:
      - "8001:8000"
  ml-service:
    build: .
    ports:
      - "8002:8000"
  api-server:
    build: .
    ports:
      - "8003:8000"
  redis:
    image: redis:7.2
    ports:
      - "6379:6379"
  mysql:
    image: mysql:8.0
    env_file: .env
  elasticsearch:
    image:
  kibana:
    image:
  nginx:
    image: nginx:alpine
    ports: "8080:80"
    

    
